import {useEffect,useState} from 'react';
import {api} from '../api';
import type {PaginatedAudit} from '../types';
const empty:PaginatedAudit={items:[],total:0,page:1,page_size:20};
const labels:Record<string,string>={'cash.open':'Apertura de caja','cash.close':'Cierre de caja','cash.reopen':'Reapertura de caja','cash.charge':'Cargo de caja','cash.print_history':'Impresión de corte','sale.create':'Venta registrada','table.checkout':'Mesa cobrada','table.cancel':'Mesa cancelada','table.item_cancel':'Producto cancelado','table.transfer':'Traspaso de productos','user.create':'Usuario creado','user.update':'Usuario modificado','permissions.update':'Permisos modificados','config.update':'Configuración modificada'};
export function AuditPage({onNotice}:{onNotice:(message:string,error?:boolean)=>void}){
 const [data,setData]=useState(empty),[page,setPage]=useState(1),[day,setDay]=useState(''),[action,setAction]=useState('');
 useEffect(()=>{api.audit(page,day,action).then(setData).catch(error=>onNotice((error as Error).message,true))},[page,day,action]);
 return <><div className="section-title"><div><h2>Auditoría</h2><p>Registro inalterable de operaciones sensibles realizadas por los usuarios.</p></div></div><section className="panel data-panel"><div className="filters"><label className="field">Día<input type="date" value={day} onChange={event=>{setDay(event.target.value);setPage(1)}}/></label><label className="field">Operación<select value={action} onChange={event=>{setAction(event.target.value);setPage(1)}}><option value="">Todas</option>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div><div className="table-wrap"><table><thead><tr><th>Fecha y hora</th><th>Usuario</th><th>Perfil</th><th>Operación</th><th>Elemento</th><th>Detalle</th></tr></thead><tbody>{data.items.map(item=><tr key={item.id}><td>{new Date(item.created_at).toLocaleString('es-MX')}</td><td><b>{item.user_name}</b></td><td>{item.user_role}</td><td>{labels[item.action]||item.action}</td><td>{item.entity_type}{item.entity_id?` #${item.entity_id}`:''}</td><td><small>{Object.entries(item.details).map(([key,value])=>`${key}: ${typeof value==='object'?JSON.stringify(value):String(value)}`).join(' · ')||'—'}</small></td></tr>)}{!data.items.length&&<tr><td colSpan={6}>No hay eventos para los filtros seleccionados.</td></tr>}</tbody></table></div>{data.total>data.page_size&&<footer className="pagination"><button disabled={page===1} onClick={()=>setPage(value=>value-1)}>← Anterior</button><span>{(page-1)*20+1}–{Math.min(page*20,data.total)} de {data.total}</span><button disabled={page*20>=data.total} onClick={()=>setPage(value=>value+1)}>Siguiente →</button></footer>}</section></>;
}
