import {Code2,Printer,Save} from 'lucide-react';
import {FormEvent,useEffect,useState} from 'react';
import {api} from '../api';
import type {BusinessConfig,Permissions,Printer as PrinterType} from '../types';

const empty:BusinessConfig={business_name:'',address:'',phone:'',ticket_message:'',printer_name:'',encoding:'cp850',character_table:null};

export function SettingsPage({permissions,onPermissions,onSaved,onNotice}:{permissions:Permissions;onPermissions:(p:Permissions)=>void;onSaved:(c:BusinessConfig)=>void;onNotice:(m:string,e?:boolean)=>void}){
 const [form,setForm]=useState(empty),[printers,setPrinters]=useState<PrinterType[]>([]),[saving,setSaving]=useState(false),[savingDeveloper,setSavingDeveloper]=useState(false),[developerMode,setDeveloperMode]=useState(permissions.developer_mode);
 useEffect(()=>{Promise.all([api.config(),api.printers()]).then(([c,p])=>{setForm(c);setPrinters(p)}).catch(e=>onNotice(e.message,true))},[]);
 useEffect(()=>setDeveloperMode(permissions.developer_mode),[permissions.developer_mode]);
 const field=(key:keyof BusinessConfig,value:string|number|null)=>setForm(current=>({...current,[key]:value}));
 async function save(event:FormEvent){event.preventDefault();setSaving(true);try{const result=await api.saveConfig(form);setForm(result.config);onSaved(result.config);onNotice(result.message)}catch(error){onNotice((error as Error).message,true)}finally{setSaving(false)}}
 async function saveDeveloper(){setSavingDeveloper(true);try{const saved=await api.savePermissions({...permissions,developer_mode:developerMode});onPermissions(saved);onNotice('Opciones de desarrollador actualizadas')}catch(error){onNotice((error as Error).message,true)}finally{setSavingDeveloper(false)}}
 async function diagnose(){try{onNotice((await api.diagnose()).message)}catch(error){onNotice((error as Error).message,true)}}
 return <><div className="section-title"><div><h2>Datos del negocio</h2><p>Esta información aparece en tus tickets y define la impresora activa.</p></div></div><form className="panel settings-form" onSubmit={save}><label className="field">Nombre del negocio<input required value={form.business_name} onChange={e=>field('business_name',e.target.value)}/></label><label className="field">Teléfono<input value={form.phone} onChange={e=>field('phone',e.target.value)}/></label><label className="field wide">Dirección<input value={form.address} onChange={e=>field('address',e.target.value)}/></label><label className="field wide">Mensaje final del ticket<input value={form.ticket_message} onChange={e=>field('ticket_message',e.target.value)}/></label><label className="field">Impresora<select value={form.printer_name} onChange={e=>field('printer_name',e.target.value)}><option value="">Seleccionar…</option>{printers.map(p=><option key={p.name} value={p.name}>{p.name}{p.default?' · predeterminada':''}</option>)}</select></label><label className="field">Encoding<input value={form.encoding} onChange={e=>field('encoding',e.target.value)}/></label><label className="field">Tabla de caracteres<select value={form.character_table??''} onChange={e=>field('character_table',e.target.value===''?null:Number(e.target.value))}><option value="">Predeterminada</option>{[0,1,2,3,4,5,16,17,18,19,255].map(n=><option key={n} value={n}>{n}</option>)}</select></label><div className="settings-actions wide"><button type="button" className="secondary" onClick={diagnose}><Printer size={17}/> Diagnosticar caracteres</button><button className="primary" disabled={saving}><Save size={17}/>{saving?'Guardando…':'Guardar configuración'}</button></div></form><section className="panel developer-settings"><header><Code2 size={20}/><div><h3>Opciones de desarrollador</h3><p>Prueba los tickets sin consumir papel.</p></div></header><label className="check-field"><input type="checkbox" checked={developerMode} onChange={event=>setDeveloperMode(event.target.checked)}/><span>Usar tickets virtuales<small>Genera una vista previa y bloquea el envío físico a la impresora.</small></span></label><button className="primary" disabled={savingDeveloper||developerMode===permissions.developer_mode} onClick={()=>void saveDeveloper()}><Save size={16}/>{savingDeveloper?'Guardando…':'Guardar opción'}</button></section></>;
}
