import {ChevronDown,KeyRound,Plus,Save,ShieldCheck,SlidersHorizontal,UserRoundCheck,UsersRound} from 'lucide-react';
import {FormEvent,useEffect,useState} from 'react';
import {api} from '../api';
import {Modal} from '../components/Modal';
import type {OperationMode,Permissions,User,UserRole} from '../types';

const roles:{id:UserRole;name:string;description:string}[]=[{id:'admin',name:'Administrador',description:'Control total, configuración, productos y usuarios.'},{id:'cashier',name:'Caja',description:'Ventas, cobro de mesas, reportes y corte de caja.'},{id:'waiter',name:'Mesero',description:'Apertura de mesas, pedidos y consulta de consumos.'}];
type ModeKey='waiter_product_transfer_mode'|'cashier_product_transfer_mode'|'waiter_table_transfer_mode'|'cashier_table_transfer_mode'|'waiter_cancel_mode'|'cashier_cancel_mode'|'cashier_discount_mode';
type PasswordKind='product_transfer'|'table_transfer'|'cancel'|'discount';

export function UsersPage({permissions,onPermissions,onNotice}:{permissions:Permissions;onPermissions:(permissions:Permissions)=>void;onNotice:(message:string,error?:boolean)=>void}){
 const [users,setUsers]=useState<User[]>([]),[editing,setEditing]=useState<User|null|undefined>(undefined),[name,setName]=useState(''),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[role,setRole]=useState<UserRole>('waiter'),[saving,setSaving]=useState(false);
 const [policy,setPolicy]=useState(permissions),[passwords,setPasswords]=useState<Record<PasswordKind,string>>({product_transfer:'',table_transfer:'',cancel:'',discount:''}),[passwordsOpen,setPasswordsOpen]=useState(false);
 useEffect(()=>setPolicy(permissions),[permissions]);
 const load=()=>api.users().then(setUsers).catch(error=>onNotice(error.message,true));useEffect(()=>{void load()},[]);
 function open(user:User|null){setEditing(user);setName(user?.display_name??'');setUsername(user?.username??'');setPassword('');setRole(user?.role??'waiter')}
 async function save(event:FormEvent){event.preventDefault();setSaving(true);try{if(editing)await api.updateUser(editing.id,{display_name:name,role,...(password?{password}:{})});else await api.createUser({display_name:name,username,password,role});setEditing(undefined);await load();onNotice(editing?'Usuario actualizado':'Usuario creado')}catch(error){onNotice((error as Error).message,true)}finally{setSaving(false)}}
 async function toggle(user:User){try{await api.updateUser(user.id,{active:!user.active});await load();onNotice(user.active?'Usuario desactivado':'Usuario activado')}catch(error){onNotice((error as Error).message,true)}}
 async function savePolicy(){const entered=Object.entries(passwords).filter(([,value])=>value.trim());if(entered.some(([,value])=>value.trim().length<4))return onNotice('Las contraseñas operativas deben tener al menos 4 caracteres',true);const {cancel_password_configured,product_transfer_password_configured,table_transfer_password_configured,discount_password_configured,...editablePolicy}=policy;void cancel_password_configured;void product_transfer_password_configured;void table_transfer_password_configured;void discount_password_configured;const passwordValues=Object.fromEntries(entered.map(([key,value])=>[`${key}_password`,value.trim()]));setSaving(true);try{const saved=await api.savePermissions({...editablePolicy,...passwordValues});setPolicy(saved);setPasswords({product_transfer:'',table_transfer:'',cancel:'',discount:''});onPermissions(saved);onNotice('Permisos y contraseñas actualizados')}catch(error){onNotice((error as Error).message,true)}finally{setSaving(false)}}
 const selector=(label:string,key:ModeKey,description:string)=><label className="permission-control"><span><b>{label}</b><small>{description}</small></span><select value={policy[key]} onChange={event=>setPolicy(current=>({...current,[key]:event.target.value as OperationMode}))}><option value="allowed">Permitido</option><option value="password">Con contraseña</option><option value="denied">Bloqueado</option></select></label>;
 const passwordRow=(kind:PasswordKind,label:string,configured:boolean)=><label className="password-row"><span><b>{label}</b><small>{configured?'Contraseña configurada':'Sin contraseña configurada'}</small></span><input type="password" minLength={4} value={passwords[kind]} onChange={event=>setPasswords(current=>({...current,[kind]:event.target.value}))} placeholder={configured?'Cambiar contraseña':'Sin contraseña configurada'}/></label>;
 return <>
  <div className="section-title"><div><h2>Usuarios y perfiles</h2><p>Asigna a cada persona únicamente las funciones que necesita.</p></div><button className="primary" onClick={()=>open(null)}><Plus size={17}/> Nuevo usuario</button></div>
  <section className="panel permissions-panel"><header><SlidersHorizontal size={19}/><div><h3>Permisos operativos</h3><p>Los permisos de Mesero y Caja se administran por separado.</p></div></header>
   <div className="permission-columns">
    <section className="permission-role"><header><UsersRound size={18}/><div><h4>Mesero</h4><p>Operaciones durante la atención de sus propias mesas.</p></div></header><label className="check-field"><input type="checkbox" checked={policy.waiter_print_account} onChange={event=>setPolicy(current=>({...current,waiter_print_account:event.target.checked}))}/><span>Imprimir cuenta<small>Sin cobrar ni cerrar la mesa.</small></span></label><label className="check-field"><input type="checkbox" checked={policy.waiter_require_guest_count} onChange={event=>setPolicy(current=>({...current,waiter_require_guest_count:event.target.checked}))}/><span>Solicitar comensales<small>Al abrir una mesa.</small></span></label>{selector('Traspasar productos','waiter_product_transfer_mode','Solo entre sus propias mesas.')}{selector('Traspasar mesa','waiter_table_transfer_mode','Asigna la mesa completa a otro mesero.')}{selector('Cancelar productos','waiter_cancel_mode','Cancela productos de sus mesas.')}</section>
    <section className="permission-role"><header><UserRoundCheck size={18}/><div><h4>Caja</h4><p>Operaciones de cobro y apoyo sobre mesas abiertas.</p></div></header><label className="check-field"><input type="checkbox" checked={policy.cashier_table_access} onChange={event=>setPolicy(current=>({...current,cashier_table_access:event.target.checked}))}/><span>Acceder a Mesas<small>Comandar y consultar mesas.</small></span></label><label className="check-field"><input type="checkbox" checked={policy.print_on_checkout} onChange={event=>setPolicy(current=>({...current,print_on_checkout:event.target.checked}))}/><span>Imprimir al cobrar<small>Genera el ticket del cobro.</small></span></label>{selector('Traspasar productos','cashier_product_transfer_mode','Entre todas las mesas abiertas.')}{selector('Traspasar mesa','cashier_table_transfer_mode','Asigna la mesa completa a otro mesero.')}{selector('Cancelar productos','cashier_cancel_mode','Cancela productos antes del cobro.')}{selector('Aplicar descuentos','cashier_discount_mode','En ventas y mesas.')}</section>
   </div>
   <div className="tip-policy-grid"><section><label className="check-field"><input type="checkbox" checked={policy.include_tip_in_ticket} onChange={event=>setPolicy(current=>({...current,include_tip_in_ticket:event.target.checked,include_suggested_tip:event.target.checked?false:current.include_suggested_tip}))}/><span>Cargo de servicio obligatorio<small>Se suma al total de la cuenta.</small></span></label><label className="field">Porcentaje de servicio<input disabled={!policy.include_tip_in_ticket} type="number" min="0" max="100" value={policy.service_charge_percent} onChange={event=>setPolicy(current=>({...current,service_charge_percent:Number(event.target.value)}))}/></label></section><section><label className="check-field"><input type="checkbox" checked={policy.include_suggested_tip} onChange={event=>setPolicy(current=>({...current,include_suggested_tip:event.target.checked,include_tip_in_ticket:event.target.checked?false:current.include_tip_in_ticket}))}/><span>Propina sugerida<small>Solo se muestra como referencia.</small></span></label><label className="field">Porcentaje sugerido<input disabled={!policy.include_suggested_tip} type="number" min="0" max="100" value={policy.suggested_tip_percent} onChange={event=>setPolicy(current=>({...current,suggested_tip_percent:Number(event.target.value)}))}/></label></section></div>
   <section className={`password-section ${passwordsOpen?'is-open':''}`}><button type="button" className="password-section-toggle" aria-expanded={passwordsOpen} onClick={()=>setPasswordsOpen(value=>!value)}><KeyRound size={18}/><span><b>Contraseñas operativas</b><small>Independientes del acceso del administrador.</small></span><ChevronDown size={18}/></button>{passwordsOpen&&<div className="password-grid"><div>{passwordRow('product_transfer','Traspaso de productos',policy.product_transfer_password_configured)}{passwordRow('table_transfer','Traspaso de mesas',policy.table_transfer_password_configured)}</div><div>{passwordRow('cancel','Cancelación de productos',policy.cancel_password_configured)}{passwordRow('discount','Aplicación de descuentos',policy.discount_password_configured)}</div></div>}</section>
   <div className="printed-table-permissions"><section><b>Cuenta impresa · Mesero</b><label className="check-field"><input type="checkbox" checked={policy.waiter_reopen_printed_table} onChange={event=>setPolicy(current=>({...current,waiter_reopen_printed_table:event.target.checked}))}/><span>Reabrir mesa<small>Permite volver a modificar el consumo.</small></span></label><label className="check-field"><input type="checkbox" checked={policy.waiter_reprint_account} onChange={event=>setPolicy(current=>({...current,waiter_reprint_account:event.target.checked}))}/><span>Reimprimir cuenta<small>Permite generar otra copia.</small></span></label></section><section><b>Cuenta impresa · Caja</b><label className="check-field"><input type="checkbox" checked={policy.cashier_reopen_printed_table} onChange={event=>setPolicy(current=>({...current,cashier_reopen_printed_table:event.target.checked}))}/><span>Reabrir mesa<small>Permite volver a modificar el consumo.</small></span></label><label className="check-field"><input type="checkbox" checked={policy.cashier_reprint_account} onChange={event=>setPolicy(current=>({...current,cashier_reprint_account:event.target.checked}))}/><span>Reimprimir cuenta<small>Permite generar otra copia.</small></span></label></section></div>
   <footer><button className="primary" disabled={saving} onClick={()=>void savePolicy()}><Save size={16}/>{saving?'Guardando…':'Guardar configuración'}</button></footer>
  </section>
  <div className="role-overview">{roles.map(item=><article className="panel" key={item.id}>{item.id==='admin'?<ShieldCheck/>:item.id==='cashier'?<UserRoundCheck/>:<UsersRound/>}<div><b>{item.name}</b><p>{item.description}</p></div></article>)}</div>
  <section className="panel data-panel"><div className="table-wrap"><table><thead><tr><th>Nombre</th><th>Usuario</th><th>Perfil</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{users.map(user=><tr key={user.id}><td><b>{user.display_name}</b></td><td>{user.username}</td><td>{roles.find(item=>item.id===user.role)?.name}</td><td><span className={`badge ${user.active?'success':'muted'}`}>{user.active?'Activo':'Inactivo'}</span></td><td><div className="actions"><button onClick={()=>open(user)}>Editar</button><button className={user.active?'danger-text':''} onClick={()=>void toggle(user)}>{user.active?'Desactivar':'Activar'}</button></div></td></tr>)}</tbody></table></div></section>
  {editing!==undefined&&<Modal title={editing?'Editar usuario':'Nuevo usuario'} onClose={()=>setEditing(undefined)}><form className="form" onSubmit={save}><label className="field">Nombre completo<input required minLength={2} value={name} onChange={e=>setName(e.target.value)}/></label>{!editing&&<label className="field">Usuario<input required minLength={3} value={username} onChange={e=>setUsername(e.target.value)}/></label>}<label className="field">{editing?'Nueva contraseña (opcional)':'Contraseña'}<input required={!editing} minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder={editing?'Dejar vacía para conservarla':'Mínimo 8 caracteres'}/></label><label className="field">Perfil<select value={role} onChange={e=>setRole(e.target.value as UserRole)}>{roles.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><div className="role-permission"><KeyRound size={17}/><span>{roles.find(item=>item.id===role)?.description}</span></div><button className="primary full" disabled={saving}>{saving?'Guardando…':'Guardar usuario'}</button></form></Modal>}
 </>;
}
