import type {AuthStatus,BusinessConfig,CashSummary,Category,DiningTable,PaginatedAudit,PaginatedCash,PaginatedSales,Permissions,Printer,Product,ProductReport,Sale,TableCancellation,User} from './types';
export class ApiError extends Error{status:number;constructor(message:string,status:number){super(message);this.status=status}}
async function request<T>(url:string,init:RequestInit={}):Promise<T>{const response=await fetch(url,{headers:{'Content-Type':'application/json'},...init});let data:unknown={};try{data=await response.json()}catch{}if(!response.ok){const payload=data as {detail?:{message?:string};message?:string};throw new ApiError(payload.detail?.message||payload.message||'Error de comunicación',response.status)}const virtual=(data as {virtual_ticket?:string})?.virtual_ticket;if(virtual)window.dispatchEvent(new CustomEvent('virtual-ticket',{detail:virtual}));return data as T}
export const api={
 authStatus:()=>request<AuthStatus>('/api/auth/status'),setup:(body:object)=>request<{user:User}>('/api/auth/setup',{method:'POST',body:JSON.stringify(body)}),login:(body:object)=>request<{user:User}>('/api/auth/login',{method:'POST',body:JSON.stringify(body)}),logout:()=>request('/api/auth/logout',{method:'POST'}),users:()=>request<User[]>('/api/users'),createUser:(body:object)=>request<User>('/api/users',{method:'POST',body:JSON.stringify(body)}),updateUser:(id:number,body:object)=>request<User>(`/api/users/${id}`,{method:'PUT',body:JSON.stringify(body)}),
 permissions:()=>request<Permissions>('/api/permissions'),savePermissions:(body:Permissions)=>request<Permissions>('/api/permissions',{method:'PUT',body:JSON.stringify(body)}),
 products:(inactive=false)=>request<Product[]>(`/api/products${inactive?'?include_inactive=true':''}`),
 createProduct:(body:object)=>request<Product>('/api/products',{method:'POST',body:JSON.stringify(body)}),
 updateProduct:(id:number,body:object)=>request<Product>(`/api/products/${id}`,{method:'PUT',body:JSON.stringify(body)}),
 deactivateProduct:(id:number)=>request<Product>(`/api/products/${id}`,{method:'DELETE'}),
 categories:()=>request<Category[]>('/api/categories'),createCategory:(name:string)=>request<Category>('/api/categories',{method:'POST',body:JSON.stringify({name})}),updateCategory:(id:number,name:string)=>request<Category>(`/api/categories/${id}`,{method:'PUT',body:JSON.stringify({name})}),deleteCategory:(id:number)=>request(`/api/categories/${id}`,{method:'DELETE'}),
 sales:(page=1,day='')=>request<PaginatedSales>(`/api/sales-history?${new URLSearchParams(Object.fromEntries(Object.entries({page:String(page),page_size:'10',day}).filter(([,v])=>v)))}`),sale:(id:number)=>request<Sale>(`/api/sales/${id}`),createSale:(body:object)=>request<{message:string;print_success:boolean|null;sale:Sale}>('/api/sales',{method:'POST',body:JSON.stringify(body)}),reprint:(id:number)=>request<{message:string}>(`/api/sales/${id}/print`,{method:'POST'}),
 report:(from:string,to:string,category='')=>request<ProductReport>(`/api/reports/products-sold?${new URLSearchParams(Object.fromEntries(Object.entries({date_from:from,date_to:to,category}).filter(([,v])=>v)))}`),
 tables:()=>request<DiningTable[]>('/api/tables'),createTable:(name:string,guest_count=0,waiter_id?:number)=>request<DiningTable>('/api/tables',{method:'POST',body:JSON.stringify({name,guest_count,waiter_id})}),waiters:()=>request<User[]>('/api/staff/waiters'),assignTableWaiter:(tableId:number,waiter_id:number,operation_password?:string)=>request<DiningTable>(`/api/tables/${tableId}/waiter`,{method:'PUT',body:JSON.stringify({waiter_id,operation_password})}),addTableItems:(id:number,items:{product_id:number;quantity:number}[])=>request<DiningTable>(`/api/tables/${id}/items`,{method:'POST',body:JSON.stringify({items})}),cancelTable:(id:number)=>request<{message:string}>(`/api/tables/${id}`,{method:'DELETE'}),printTableAccount:(id:number)=>request<{message:string}>(`/api/tables/${id}/print-account`,{method:'POST'}),tableCancellations:(id:number)=>request<TableCancellation[]>(`/api/tables/${id}/cancellations`),cancelTableItem:(tableId:number,itemId:number,body:object)=>request<DiningTable>(`/api/tables/${tableId}/items/${itemId}/cancel`,{method:'POST',body:JSON.stringify(body)}),transferTableItems:(tableId:number,body:object)=>request<{source:DiningTable;target:DiningTable}>(`/api/tables/${tableId}/transfer`,{method:'POST',body:JSON.stringify(body)}),checkoutTable:(id:number,body:object)=>request<{message:string;print_success:boolean|null;sale:Sale}>(`/api/tables/${id}/checkout`,{method:'POST',body:JSON.stringify(body)}),
 cash:()=>request<{open:boolean;session:CashSummary|null}>('/api/cash/current'),openCash:(opening_amount:string)=>request<{session:CashSummary}>('/api/cash/open',{method:'POST',body:JSON.stringify({opening_amount})}),addCashCharge:(body:{amount:string;concept:string})=>request<{message:string;summary:CashSummary}>('/api/cash/charges',{method:'POST',body:JSON.stringify(body)}),closeCash:(body:{declared_cash:string;declared_card:string;declared_transfer:string})=>request<{message:string;summary:CashSummary;print_success:boolean|null}>('/api/cash/close',{method:'POST',body:JSON.stringify(body)}),printCash:()=>request<{message:string}>('/api/cash/print',{method:'POST'}),cashHistory:(page=1)=>request<PaginatedCash>(`/api/cash/history?page=${page}&page_size=10`),cashHistoryDetail:(id:number)=>request<CashSummary>(`/api/cash/history/${id}`),reopenCash:(id:number,reason:string)=>request<{message:string;session:CashSummary}>(`/api/cash/history/${id}/reopen`,{method:'POST',body:JSON.stringify({reason})}),printHistoricalCash:(id:number)=>request<{message:string}>(`/api/cash/history/${id}/print`,{method:'POST'}),
 audit:(page=1,day='',action='')=>request<PaginatedAudit>(`/api/audit?${new URLSearchParams(Object.fromEntries(Object.entries({page:String(page),page_size:'20',day,action}).filter(([,value])=>value)))}`),
 config:()=>request<BusinessConfig>('/api/config'),printers:()=>request<Printer[]>('/api/printers'),saveConfig:(body:BusinessConfig)=>request<{message:string;config:BusinessConfig}>('/api/config',{method:'PUT',body:JSON.stringify(body)}),diagnose:()=>request<{message:string}>('/api/print/character-table-test',{method:'POST'})
};
