export type PaymentMethod='cash'|'card'|'transfer';
export interface Product{id:number;name:string;price:string;category:string;active:boolean;created_at:string;updated_at:string}
export interface Category{id:number;name:string;active:boolean;created_at:string;updated_at:string}
export interface SaleItem{id:number;product_id:number|null;product_name:string;unit_price:string;quantity:number;subtotal:string}
export interface Sale{id:number;folio:string;subtotal:string;total:string;discount_amount:string;discount_reason:string;tip_amount:string;tip_method:PaymentMethod|null;service_charge_percent:number;grand_total:string;payment_method:PaymentMethod|'mixed';payments?:{method:PaymentMethod;amount:string}[];amount_received:string|null;change_amount:string|null;created_at:string;cash_session_id:number;guest_count:number;items?:SaleItem[]}
export interface CashSummary{id:number;opened_at:string;closed_at:string|null;opening_amount:string;operations:number;cash:string;card:string;transfer:string;tip_cash:string;tip_card:string;tip_transfer:string;total_tips:string;paid_tips:string;total_sold:string;grand_total:string;total_collected:string;charges:string;net_total:string;expected_cash:string;cancelled_accounts:number;discounted_accounts:number;total_discounts:string;average_consumption:string;guests:number;declared_cash:string|null;declared_card:string|null;declared_transfer:string|null;declared_total:string|null;cash_variance:string|null;reopened_count:number;last_reopened_at:string|null;last_reopened_by:string;last_reopen_reason:string}
export interface PaginatedCash{items:CashSummary[];total:number;page:number;page_size:number}
export interface AuditEvent{id:number;user_id:number|null;user_name:string;user_role:string;action:string;entity_type:string;entity_id:string;details:Record<string,unknown>;created_at:string}
export interface PaginatedAudit{items:AuditEvent[];total:number;page:number;page_size:number}
export interface BusinessConfig{business_name:string;address:string;phone:string;ticket_message:string;printer_name:string;encoding:string;character_table:number|null}
export interface ProductReport{total_units:number;distinct_products:number;total_revenue:string;total_visitors:number;products:{product_id:number|null;product_name:string;category:string;quantity:number;revenue:string;sales_count:number}[]}
export interface PaginatedSales{items:Sale[];total:number;page:number;page_size:number}
export interface Printer{name:string;default:boolean}
export interface CartLine{product:Product;quantity:number}
export interface DiningTableItem{id:number;product_id:number;product_name:string;unit_price:string;quantity:number;subtotal:string;added_at:string}
export interface DiningTable{id:number;name:string;status:'open'|'closed'|'cancelled';guest_count:number;assigned_waiter_id:number|null;assigned_waiter_name:string;opened_at:string;updated_at:string;closed_at:string|null;account_printed_at:string|null;total:string;items:DiningTableItem[]}
export interface TableCancellation{id:number;product_name:string;quantity:number;amount:string;reason:string;cancelled_by:string;cancelled_at:string}
export type UserRole='admin'|'cashier'|'waiter';
export interface User{id:number;username:string;display_name:string;role:UserRole;active:boolean;created_at:string}
export interface AuthStatus{setup_required:boolean;authenticated:boolean;user:User|null}
export type OperationMode='allowed'|'password'|'denied';
export interface Permissions{cashier_table_access:boolean;waiter_print_account:boolean;waiter_product_transfer_mode:OperationMode;cashier_product_transfer_mode:OperationMode;waiter_table_transfer_mode:OperationMode;cashier_table_transfer_mode:OperationMode;waiter_cancel_mode:OperationMode;cashier_cancel_mode:OperationMode;cashier_discount_mode:OperationMode;waiter_reopen_printed_table:boolean;cashier_reopen_printed_table:boolean;waiter_reprint_account:boolean;cashier_reprint_account:boolean;cancel_password_configured:boolean;product_transfer_password_configured:boolean;table_transfer_password_configured:boolean;discount_password_configured:boolean;include_tip_in_ticket:boolean;service_charge_percent:number;include_suggested_tip:boolean;suggested_tip_percent:number;print_on_checkout:boolean;waiter_require_guest_count:boolean;developer_mode:boolean}
